name:                AetherlingSTIR
version:             0.1.0.0
github:              "David-Durst/Aetherling/theory/AetherlingSTIR"
license:             BSD3
author:              "David Durst"
maintainer:          "davidbdurst@gmail.com"
copyright:           "2018 David Durst"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/David-Durst/Aetherling/theory/AetherlingSTIR#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-simple >= 2.1.0.0 && < 2.2.0.0

library:
  source-dirs: src/lib/

executables:
  AetherlingSTIR-Example-exe:
    main:                Main.hs
    source-dirs:         src/examples/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AetherlingSTIR

tests:
  AetherlingSTIR-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AetherlingSTIR
